### ISSUE TITLE
For a Data processing App from Cloudant changes GitHub repo exists with all the code a user needs to build out the use case example

### ISSUE THREAD

**Issue by krook** [IBM/openwhisk-data-processing-cloudant#4]

**Comment by krook** [comment]
1. Log into the Bluemix console and create a Cloudant instance named `openwhisk-getting-started`.  Use the Cloudant dashboard to create a new database called `ogs`. Gather the credentials and save them to `secret.sh`.

2. Bind the Cloudant package in the OpenWhisk command line tool.
```bash
wsk package bind /whisk.system/cloudant "$CLOUDANT_INSTANCE" \
  --param username "$CLOUDANT_USER" \
  --param password "$CLOUDANT_PASS" \
  --param host "$CLOUDANT_USER.cloudant.com"
```

3. Create the action that writes contextual generated data (like the time) to Cloudant, using package variables to inject credentials. We should perhaps also show both text and binary data inserted as an attachment.
```bash
wsk action create write-to-cloudant actions/write-to-cloudant.js \
  --param CLOUDANT_USER "$CLOUDANT_USER" \
  --param CLOUDANT_PASS "$CLOUDANT_PASS" \
  --param CLOUDANT_ARCHIVED_DATABASE "$CLOUDANT_DATABASE"
```

4. Create the action that reads from Cloudant, and echos it to the console, and returns a JSON object with the same info, using package variables to inject credentials.
```bash
$WSK action create write-from-cloudant actions/write-from-cloudant.js \
  --param CLOUDANT_USER "$CLOUDANT_USER" \
  --param CLOUDANT_PASS "$CLOUDANT_PASS" \
  --param CLOUDANT_AUDITED_DATABASE "$CLOUDANT_DATABASE"
```

**Comment by jzaccone** [comment]
As I understand how openwhisk works... to implement with Image data, we need to configure an Image source. Some options:

1) Follow the [open-checks](https://github.com/krook/openchecks) pattern where the user uploads an image using the console, and we have a trigger that polls that as a source
2) Use twitter API or some external source to get an image. e.g. latest image post from #openwhisk
3) Upload static images as part of a zip file with the action and use these when the `write-to-cloudant` action is invoked. (perhaps select a different image based on time)

Any other options?
...

4) Keep this example simpler and just use random (timestamp) text data.

**Comment by jzaccone** [comment]
After talking with Daniel, we decided to just find a URL for an i.e. IBM logo.

**Comment by krook** [comment]
As @jzaccone noted, the simplest use case is just to download an image over HTTP and stream that into Cloudant, rather than package binary data within this repo or pass it to the action as a parameter.

**Comment by krook** [comment]
Done.
